### ISSUE TITLE
Abandoned package

### ISSUE THREAD

**Issue by michielkenis** [hanoii/platformsh2slack#3]
Hi, 
First of all, awesome integration!! I'm still trying to figure out how to implement this into my Platform.sh packages, but for now, I get an issue when I try to install this locally. 

I get this message:
`Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.`

Any clue on how to fix this?

**Comment by hanoii** [comment]
I am not sure how you are using this library, but `egeloen/http-adapter` is not a dependency of this package (or any of its dependencies).

The README should be enough I think. This is meant to be used either standalone or as part as a bigger PHP composer project.

Try running `composer require hanoii/platformsh2slack` on an empty dir, it will properly get everything and allow you to start using it.
